server:
  port: 8080
  servlet:
    context-path: /san_ptop_provider
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ptp
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.31.168
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  data:
    mongodb:
      host: 192.168.31.97
      port: 27017
      database: logs
    solr:
     host: http://localhost:8899/solr/mycore/
mybatis:
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapper/*.xml
rabbitmq:
  host: 192.168.31.97
  port: 5672
  username: guest
  password: guest
  publisher-confirms: true
  virtual-host: /wqw
