server:
  port: 8080
  servlet:
    context-path: /san_ptop_provider
spring:
  datasource:
    url: jdbc:mysql://192.168.31.237:3306/ptp
    username: nxb
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    port: 6379
    host: 192.168.88.128
    database: 0
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 0
  data:
    mongodb:
      host: 192.168.31.97
      port: 27017
      username: wang
mybatis:
  type-aliases-package: com.jk.model
  mapper-locations: classpath:mapper/*.xml

